# Generated by Django 2.2.6 on 2019-10-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191012_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='id_form',
        ),
        migrations.AddField(
            model_name='formulario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
