# Generated by Django 2.2.6 on 2019-10-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191016_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
