# Generated by Django 2.2.6 on 2019-10-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191016_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
