# Generated by Django 2.2.6 on 2019-11-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
