# Generated by Django 2.2.6 on 2019-11-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191031_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacioncurso',
            name='id_asignacion',
        ),
        migrations.RemoveField(
            model_name='asignacioncursolibre',
            name='id_asignacionlibre',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='id_Carrera',
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='id_Catedratico',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_Curso',
        ),
        migrations.RemoveField(
            model_name='cursolibre',
            name='id_CursoLibre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='carnet',
        ),
        migrations.RemoveField(
            model_name='login',
            name='id_login',
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacioncursolibre',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catedratico',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursolibre',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
