# Generated by Django 2.2.6 on 2019-11-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacioncurso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='asignacioncursolibre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cursolibre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='id',
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='id_asignacion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacioncursolibre',
            name='id_asignacionlibre',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_Carrera',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catedratico',
            name='id_Catedratico',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='id_Curso',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursolibre',
            name='id_CursoLibre',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='id_form',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='id_login',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_publicacion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
