# Generated by Django 2.2.6 on 2019-11-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191101_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
